repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        entry: poetry run pyright
        pass_filenames: false

      - id: pytest
        name: pytest
        language: system
        entry: poetry run pytest
        pass_filenames: false
